// What an account has spent in the last 24 hours, counted from the record of
// what actually happened.
//
// Every limit that guards the shared model key reads from here. Two rules
// hold for all of them, because the approval gate is gone and anyone signed
// in can now reach these routes:
//
//   - A rolling 24 hours on the server's clock, never a day the client names.
//     The collection cap used to count by the local date in the request, and
//     a client sending a different date each time would never run out.
//   - Counted in the database, never in memory. The Ask AI limiter kept its
//     counts in a Map, and on serverless every cold instance starts at zero —
//     it limited very little.
import { and, eq, gt, sql } from 'drizzle-orm'
import { db } from '../db/client.js'
import { collectionStarts, usageEvents } from '../db/schema.js'
import { NEW_ACCOUNTS_DAILY_MODEL_CALLS } from '../plans.js'
import { SINCE_QUOTA_RESET } from './quotaWindow.js'

const WINDOW = sql`now() - interval '24 hours'`

/** Collections started in the last 24 hours. */
export async function collectionsStartedLast24h(userId: string): Promise<number> {
  const [r] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(collectionStarts)
    .where(and(eq(collectionStarts.userId, userId), gt(collectionStarts.createdAt, WINDOW)))
  return r?.n ?? 0
}

/** Notes generated by growing collections in the last 24 hours. growSpace
 *  logs one note_write per run with the number it added. */
export async function notesGrownLast24h(userId: string): Promise<number> {
  const [r] = await db
    .select({ n: sql<number>`coalesce(sum((${usageEvents.metadata}->>'count')::int), 0)::int` })
    .from(usageEvents)
    .where(
      and(
        eq(usageEvents.userId, userId),
        eq(usageEvents.eventType, 'note_write'),
        sql`${usageEvents.metadata}->>'source' = 'grow'`,
        gt(usageEvents.createdAt, WINDOW),
      ),
    )
  return r?.n ?? 0
}

/** Ask AI messages in the last 24 hours. */
export async function askAiLast24h(userId: string): Promise<number> {
  const [r] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(usageEvents)
    .where(
      and(
        eq(usageEvents.userId, userId),
        eq(usageEvents.eventType, 'llm_call'),
        sql`${usageEvents.metadata}->>'source' = 'ask-ai'`,
        gt(usageEvents.createdAt, WINDOW),
      ),
    )
  return r?.n ?? 0
}

/** Model calls made for every not-yet-approved account together since the
 *  provider's quota last reset.
 *
 *  The one count in this file that is NOT a rolling 24 hours. The others are
 *  about fairness between accounts, where a rolling window is right. This one
 *  is a share of Gemini's daily quota, and that quota resets at midnight
 *  Pacific: counted on a rolling window it would go on charging new accounts
 *  for calls the provider has already forgiven, and keep them shut out for
 *  hours after the quota they were being protected from came back. The
 *  window is quotaWindow.ts's, the same one the cron and the backfill use. */
export async function newAccountModelCallsToday(): Promise<number> {
  const r = await db.execute(sql`
    SELECT count(*)::int AS n
    FROM usage_events e
    JOIN users u ON u.id = e.user_id
    WHERE e.event_type = 'llm_call'
      AND e.created_at >= ${SINCE_QUOTA_RESET}
      AND NOT u.access_approved AND u.role <> 'owner'
  `)
  return (r.rows[0] as { n: number } | undefined)?.n ?? 0
}

/** Is the shared allowance for new accounts spent for this quota day? */
export async function newAccountBudgetSpent(): Promise<boolean> {
  return (await newAccountModelCallsToday()) >= NEW_ACCOUNTS_DAILY_MODEL_CALLS
}

/** Said to a new account when the shared allowance is spent. It is not
 *  their doing, so it does not read like a personal limit. */
export const NEW_ACCOUNT_BUDGET_MESSAGE =
  'New accounts have used up today’s shared allowance for generating notes. Try again tomorrow — or ask to have your account approved for higher limits.'

/** Thrown by the model meter when a new account's call would go over the
 *  shared allowance. Callers that report errors to the reader can show
 *  `message` as it is. */
export class NewAccountBudgetError extends Error {
  constructor() {
    super(NEW_ACCOUNT_BUDGET_MESSAGE)
    this.name = 'NewAccountBudgetError'
  }
}
