// What each plan may do. One table, read by everything that enforces a limit.
//
// These numbers lived in three files — the flashcard builder, the questions
// route and the onboarding limits — each with its own `Record<string, …>`
// keyed by plan. That was survivable while there was one plan; adding a
// second meant editing three tables in step, which is the exact split this
// codebase keeps paying for. They are all here now, and each call site asks
// this file.
//
// `users.plan_tier` is the input. It is normally written by the Razorpay
// webhook, and the owner can set it by hand from the admin panel — see the
// note on `POST /api/admin/users/:id/plan`.

/** A limit that is not a limit. Only ever compared against, never counted
 *  up to, and never passed anywhere that would try to allocate it. */
export const UNLIMITED = Number.POSITIVE_INFINITY

export interface PlanLimits {
  /** Collections not archived. Archiving or deleting frees a slot. */
  activeCollections: number
  /** New collections started in one local day. */
  newCollectionsPerDay: number
  /** Cards in a day's deck. Never UNLIMITED: a deck is a sitting, and an
   *  infinite one is not a bigger sitting, it is a broken one. */
  flashcardsPerDay: number
  /** Questions of your own, per collection per local day. */
  customQuestionsPerDay: number
  /** Notes generated by growing collections, in any rolling 24 hours. A
   *  new collection's own starter notes do not count — that is what
   *  newCollectionsPerDay limits. */
  newNotesPerDay: number
  /** Ask AI chat messages on the shared key, in any rolling 24 hours. */
  askAiPerDay: number
}

const PLANS: Record<string, PlanLimits> = {
  // An account nobody has approved yet. This tier replaced the approval gate:
  // new sign-ups used to be locked out of everything but the demo until the
  // owner let them in, which made the first real collection wait on a
  // person. Now they get in at once, with limits tight enough that one
  // account cannot run up the shared key — and NEW_ACCOUNTS_DAILY_MODEL_CALLS
  // below caps all of them together, which is what stops a pile of throwaway
  // accounts doing it instead. Approving someone in the admin panel moves
  // them to their plan's limits.
  //
  // Approval is no longer only by hand: a three-day streak graduates an
  // account to free by itself (usage/streak.ts).
  new: {
    activeCollections: 5,
    newCollectionsPerDay: 2,
    flashcardsPerDay: 10,
    customQuestionsPerDay: 1,
    newNotesPerDay: 6,
    askAiPerDay: 5,
  },
  free: {
    activeCollections: 5,
    newCollectionsPerDay: 5,
    flashcardsPerDay: 10,
    customQuestionsPerDay: 1,
    // Measured: a reader's grown notes per day were p50 2, p90 7, max 23.
    // Doubled from ten once the model fallback chain (llm/models.ts) roughly
    // doubled the day's fast quota, to ~1,000 requests: the busiest day on
    // record was 358 calls.
    newNotesPerDay: 20,
    // Ask AI is the open-ended way to spend the shared key — a reply can be
    // asked for again and again — where every other limit here is spent on
    // notes that stay. Raised from three with the same headroom.
    askAiPerDay: 10,
  },
  pro: {
    activeCollections: UNLIMITED,
    newCollectionsPerDay: UNLIMITED,
    // A number rather than UNLIMITED, for the reason above. Twice the free
    // deck is a longer sitting; it is not a different product.
    flashcardsPerDay: 20,
    customQuestionsPerDay: UNLIMITED,
    newNotesPerDay: UNLIMITED,
    // Pro chat goes through its own route on its own key.
    askAiPerDay: UNLIMITED,
  },
}

/** Model calls all not-yet-approved accounts may spend together in one of
 *  the provider's quota days (midnight to midnight Pacific — the window
 *  Gemini's daily quota is counted in; see usage/quotaWindow.ts).
 *  Per-account limits do nothing against someone opening ten accounts; this
 *  does. 300 of the ~1,000 fast requests a day the fallback chain gives
 *  (llm/models.ts), leaving most of it for approved users whatever new
 *  accounts do. Sized against real traffic of 3-25 calls a day
 *  in total, so it is not something genuine new users meet — a collection
 *  is about 6-8 calls, so this is room for roughly forty new collections a
 *  day before anything is refused. */
export const NEW_ACCOUNTS_DAILY_MODEL_CALLS = 300

/** Which limits apply to this account. Pro wins outright: it is either
 *  paid for or granted by hand from the admin panel, and in both cases the
 *  point is the higher limits, approved or not. Otherwise unapproved
 *  accounts are on the 'new' tier whatever plan their row says; owners are
 *  always approved (see resolveSession), so they never land here. */
export function tierOf(user: { accessApproved: boolean; planTier?: string | null }): string {
  if (user.planTier === 'pro') return 'pro'
  return user.accessApproved ? (user.planTier ?? 'free') : 'new'
}

/** Unknown tiers get the free limits. A plan string nobody recognises is
 *  more likely a typo or a stale row than an entitlement. */
export function limitsFor(planTier?: string | null): PlanLimits {
  return PLANS[planTier ?? 'free'] ?? PLANS.free
}

export function isUnlimited(n: number): boolean {
  return !Number.isFinite(n)
}

/** For copy: "3 left today" reads badly when the answer is "as many as you
 *  like". Callers that show a count use this to decide whether to. */
export function remainingOf(limit: number, used: number): number | null {
  return isUnlimited(limit) ? null : Math.max(0, limit - used)
}

// The tiers a plan can be *set* to. 'new' is deliberately not one: it is a
// state an account is in until approved, not a plan anyone chooses.
export const PLAN_TIERS = ['free', 'pro'] as const
export type PlanTier = (typeof PLAN_TIERS)[number]

export function isPlanTier(v: unknown): v is PlanTier {
  return typeof v === 'string' && (PLAN_TIERS as readonly string[]).includes(v)
}
